# Generated by Django 3.1.6 on 2021-03-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('head-teacher', 'Хед-тічер'), ('mentor', 'Ментор'), ('tutor', 'Тьютор'), ('student', 'Студент'), ('parent', 'Батьки'), ('guest', 'Гість')], max_length=15),
        ),
    ]
