# Generated by Django 3.1.6 on 2021-03-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_price'),
        ('account', '0003_auto_20210304_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prostudent',
            name='tutor_fk',
        ),
        migrations.RemoveField(
            model_name='protutor',
            name='mentor_fk',
        ),
        migrations.AddField(
            model_name='protutor',
            name='courses',
            field=models.ManyToManyField(related_name='tutors', to='course.Course'),
        ),
        migrations.AddField(
            model_name='protutor',
            name='head_teacher_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='account.proheadteacher'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('head-teacher', 'Хед-тічер'), ('tutor', 'Тьютор'), ('student', 'Студент'), ('parent', 'Батьки'), ('guest', 'Гість')], max_length=15),
        ),
        migrations.AlterField(
            model_name='prostudent',
            name='grade',
            field=models.CharField(choices=[('ZNO', 'ЗНО'), ('11', '11'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='ZNO', max_length=15),
        ),
        migrations.AlterField(
            model_name='prostudent',
            name='type_grade',
            field=models.CharField(choices=[('ZNO', 'ЗНО'), ('in-depth', 'Поглиблене вивчення'), ('normal', 'Рівень стандарту')], default='normal', max_length=15),
        ),
        migrations.DeleteModel(
            name='ProMentor',
        ),
    ]
