# Generated by Django 3.1.6 on 2021-03-24 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210323_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='protutor',
            name='chose_qty_students',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
