# Generated by Django 3.1.6 on 2021-04-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_question'),
        ('account', '0006_auto_20210325_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='proheadteacher',
            name='courses',
            field=models.ManyToManyField(related_name='headteachers', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='protutor',
            name='head_teacher_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors', to='account.proheadteacher'),
        ),
    ]
