# Generated by Django 3.1.6 on 2021-03-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file_fk',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_fk',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_fk',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_fk',
        ),
        migrations.AddField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
