# Generated by Django 3.1.6 on 2021-04-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210407_1221'),
        ('course', '0009_lesson_type_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('point', models.PositiveIntegerField(default=0)),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_questions', to='course.question')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_questions', to='account.prostudent')),
            ],
        ),
    ]
