# Generated by Django 3.1.6 on 2021-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_answerquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerquestion',
            old_name='point',
            new_name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
