# Generated by Django 3.1.6 on 2021-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210409_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='chose_answer',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
