# Generated by Django 3.1.6 on 2021-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_homeworkphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home_work'),
        ),
    ]
