# Generated by Django 3.1.6 on 2021-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210417_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='include_month_private_lessons_default_fk',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
