# Generated by Django 3.1.6 on 2021-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20210424_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_private_lesson',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
