# Generated by Django 3.1.6 on 2021-04-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedWorkingHoursByDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tutor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_working_hours_by_default', to='account.protutor')),
            ],
        ),
        migrations.CreateModel(
            name='MonthTutorTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_weekdays', models.TextField(default='{}')),
                ('booked_hours', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tutor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_working_time_by_default', to='account.protutor')),
            ],
        ),
    ]
