# Generated by Django 3.1.6 on 2021-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthtutortimetable',
            name='month',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='monthtutortimetable',
            name='year',
            field=models.CharField(default='2002', max_length=4),
        ),
    ]
