# Generated by Django 3.1.6 on 2021-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210417_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedworkinghoursbydefault',
            name='selected_time',
            field=models.TextField(default='[]'),
        ),
    ]
