# Generated by Django 3.1.6 on 2021-04-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20210418_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthtutortimetable',
            old_name='booked_hours',
            new_name='booked_weekdays',
        ),
    ]
