# Generated by Django 3.1.6 on 2021-04-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210417_1215'),
        ('timetable', '0005_auto_20210419_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthtutortimetable',
            name='course_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_working_time_by_default', to='course.course'),
        ),
        migrations.AlterField(
            model_name='monthtutortimetable',
            name='month',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
