# Generated by Django 3.1.6 on 2021-04-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210417_1215'),
        ('access', '0008_auto_20210421_2100'),
        ('account', '0008_profile_is_active'),
        ('timetable', '0006_auto_20210421_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthStudentTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_lesson_days', models.TextField(default='{}')),
                ('qty_finished_private_lessons', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(default='0', max_length=2)),
                ('year', models.CharField(default='2002', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_student_timetable', to='course.course')),
                ('progress_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_student_timetable', to='access.progress')),
                ('student_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_student_timetable', to='account.protutor')),
            ],
        ),
    ]
