# Generated by Django 3.1.6 on 2021-04-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_is_active'),
        ('timetable', '0007_monthstudenttimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthstudenttimetable',
            name='student_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_student_timetable', to='account.prostudent'),
        ),
    ]
