# Generated by Django 3.1.6 on 2021-03-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20210325_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.IntegerField(default=0)),
                ('lessons_opened', models.TextField(default='{}')),
                ('progress', models.TextField(default='{}')),
                ('start_sub_data', models.DateTimeField()),
                ('end_sub_data', models.DateTimeField()),
                ('student_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='account.prostudent')),
                ('tutor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_progresses', to='account.protutor')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_course', models.IntegerField(default=0)),
                ('parent_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='account.proparent')),
                ('student_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='account.prostudent')),
            ],
        ),
    ]
