# Generated by Django 3.1.6 on 2021-03-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='end_sub_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_sub_data',
            field=models.DateField(),
        ),
    ]
