# Generated by Django 3.1.6 on 2021-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_progress_current_qty_tutor_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
