# Generated by Django 3.1.6 on 2021-04-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_progress_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='current_qty_tutor_lessons',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_qty_private_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
