# Generated by Django 3.1.6 on 2021-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_auto_20210421_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='current_qty_private_lessons',
            new_name='qty_bought_private_lessons',
        ),
        migrations.AddField(
            model_name='progress',
            name='qty_finished_private_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
