# Generated by Django 3.1.6 on 2021-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_auto_20210424_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='include_month_private_lessons_default_fk',
        ),
        migrations.AddField(
            model_name='progress',
            name='include_month_private_lessons_default',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
