# Generated by Django 3.1.6 on 2021-04-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_auto_20210424_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='include_month_private_lessons_default',
            new_name='include_month_private_lessons_include_default',
        ),
    ]
