# Generated by Django 3.1.6 on 2021-04-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0008_auto_20210421_2100'),
        ('account', '0008_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('report_tutor', models.TextField(default='')),
                ('video_lesson', models.FileField(upload_to='video/private_lessons/%y')),
                ('lesson_date', models.DateTimeField(default='01.01.2002')),
                ('lesson_time', models.CharField(default='7:00-8:00', max_length=20)),
                ('checked_by_head_teacher', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('progress_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_lessons', to='access.progress')),
                ('student_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_lessons', to='account.prostudent')),
                ('tutor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_lessons', to='account.protutor')),
            ],
        ),
    ]
