# Generated by Django 3.1.6 on 2021-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelesson',
            name='lesson_date',
            field=models.DateField(default='01.01.2002'),
        ),
    ]
