# Generated by Django 3.1.6 on 2021-04-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_lesson', '0002_auto_20210421_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatelesson',
            options={'ordering': ['-lesson_date']},
        ),
    ]
